### ISSUE TITLE
Data for JUnit Test

### ISSUE THREAD

**Issue by Alimpertis39** [EvoSuite/evosuite#110]
I would like to know when a JUnit test is running, how it is initialized?
Is every test created randomly for every class? Is there any algorithm for creating JUnit test? 
If it exists, is this algorithm the same for every class?

**Comment by gofraser** [comment]
During generation, tests are generated randomly initially, and then "evolved" using a genetic algorithm. The test generation algorithm is probably best described in this [article](http://www.evosuite.org/wp-content/papercite-data/pdf/tse12_evosuite.pdf).  The same algorithm is applied to any class, but since it is a randomised algorithm, you will get different results each time you apply it (even on the same class).
