### ISSUE TITLE
Hard-coded absolute file paths generated by EvoSuite (v1.0.5)

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#122]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I generated a unit test whose corresponding production class contains methods that work with file names.  As part of the test fixture setup, EvoSuite generated a file path that reflected the project directory structure on the machine where the unit test was generated (a directory in this case):

```Java
EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\git\\myproject\\target\\classes");
```
However, when the unit test was executed on the build server, the test failed because the directory didn't exist there.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Generate a test for a file-based method that takes a string filename as a parameter
2. Run the test on the machine that generated the code. Observe that it passes.
3. Commit the code to source control.
4. Check out the code to another location on the current machine or another one with a different project root.  The intent here is that the original path does not exist on the second machine.
5. Run the test.  Observer that it fails.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

The test generated a ```FileNotFoundExecption``` instead of the expected result.
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

I would expect every test generated by evosuite to be portable, at least to the extent it will pass on any machine running the same OS.

### Additional info
*Please add any information of interest here below*

Should these types of test leverage the JUnit TemporaryFile rule?

**Comment by gofraser** [comment]
This should be fixed in 7dc24644eb87fc0ff1a7b269e27fb449d8c23543.

**Comment by JavaJimFl** [comment]
Woo hoo!  Thank you.

**Comment by gofraser** [comment]
We found an issue with this fix: Since user.dir will now be set in the generated tests to whatever it was during test generation, this will break the Jacoco agent if tests are run in a different environment (as used in your example in #120), since the Jacoco agent will try to write to jacoco.exec in whatever the test sets user.dir to. We're currently testing a workaround of avoiding that user.dir is included in the absolute path names used in EvoSuiteFile (but this might theoretically trade in some flakiness to enable Jacoco to work). Other suggestions are welcome (e.g. if there is a way to avoid Jacoco trying to locate jacoco.exec in user.dir - without setting an absolute path in the build configuration)

**Comment by gofraser** [comment]
This should be fixed now. The only caveat is that Jacoco with offline instrumentation needs to be explicitly told where the jacoco.exec file is - see http://www.evosuite.org/documentation/measuring-code-coverage/
