### ISSUE TITLE
Optimizing Evosuite Code Coverage

### ISSUE THREAD

**Issue by poojap11** [EvoSuite/evosuite#17]
Hi!

I am trying to generate unit tests for a complex project. I am not getting that great code coverage on most of the classes (0%-10%). Are there any Evosuite properties that anyone has found that can potentially optimize code coverage? I have been looking at the properties that have to do with timeouts during test generation (i.e. ctg_time...). I haven't found anything really helpful so far. 

Thank you! :)

**Comment by arcuri82** [comment]
Hi,
   it is bit strange. with default configurations, ES usually achieves an average 70% coverage, at least on the tens of thousands of classes we have applied it on. I guess might be something special in your computer / project which does crash ES. Can you please provide some more details on how your run it (command line? IntelliJ? Maven? which OS?) and is there any exception in the logs?

cheers

Andrea

**Comment by poojap11** [comment]
Hi Andrea! 

Actually I was using Eclemma to generate a code coverage report for me, however, I found that it may in inaccurate. I tried Cobertura instead and I am seeing much higher code coverage results. Thank you for your prompt reply! 

I also had a question though while looking through this report...
Is EvoSuite able to generate tests for classes that use dependency injection or not?

I also noticed that my code coverage was low when my code called services.
Other than services that need mocking, what are the types of items that EvoSuite does not generate good tests for?  

Thanks!
Pooja

**Comment by arcuri82** [comment]
Hi,
 in current configuration, you do not get coverage values for EclEmma, although it works for IntelliJ, Cobertura and should also work for JaCoCo (but haven't checked this latter in a while). This is due to how classes are instrumented. I guess we should extend documentation to explain it.

Regarding "dependency injection", short answer "no". However, it is a working in progress feature that is nearly done (still few bugs to fix), so it might come in new release in the next few weeks/months

**Comment by arcuri82** [comment]
Hi,
  I made an alpha release (still few things to fix and more testing before a proper / official release) where this issue should had been fixed. Version is 1.0.4-alpha1, on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cevosuite). If you use an executable jar instead of Maven, download the one from http://repo1.maven.org/maven2/org/evosuite/evosuite-master/1.0.4-alpha1/

can you confirm whether the issue you reported has been solved or not?  

cheers

Andrea

**Comment by gofraser** [comment]
This seems to be fixed, so I am closing this issue. If the problem re-appears, please re-open this issue.
