### ISSUE TITLE
How to generate test classes only for specific methods inside a class with EvoSuite Maven plugin

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#209]
Hi,

I understood from Issue response to #207 as how to generate Test Class for individual Classes using Maven Plugin. Going further, **is it possible to selectively generate test classes only for specific methods inside a Class?** Because if its a huge class, we don't want to generate test classes for all methods inside it every time

**Comment by jose** [comment]
`$ mvn evosuite:generate -Dcuts=org.foo.Bar -DextraArgs="-Dtarget_method_list=methodA:methodB:methodC:..."`

**Comment by jose** [comment]
Hi @anandsubram, I've just tried the option `-Dtarget_method_list=...` on a toy example and it seems to be working. Any chance you can provide the Java project you're playing with?

**Comment by anandsubram** [comment]
Sure. My aim is to generate test class only for "sum" method. I provided the command as below

**mvn evosuite:generate -Dcuts=artifact123.Calculator -DextraArgs="-Dtarget_method_lit=sum"**

Code Below:-

package artifact123;

public class Calculator 
{
	public int sum(int i,int j)
	{
		return i+j;
	}
	
	public String append(String i,String j)
	{
		return i+j;
	}
	}

**Comment by jose** [comment]
Hi @anandsubram,

I've just realised that you must specify the method signature of the method you want to test, and not the name of the method (which makes total sense). The method signature is composed by method's name, parameter types, and also the return type. (Note that the [Java language](https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html) states that "_the method signature is composed only by the method's name and the parameter types_", however the JVM also includes the return type). EvoSuite checks method signatures, instead of just method's name, to distinguish methods with the same name (as several methods with the same name can be defined in a Java class), e.g.,
```java
public class Foo {
  public void bar() {
    // ...
  }
  public void bar(boolean b) {
    // ...
  }
}
```

Having said that, if you only want to test the method `sum` you must run:
```
$ mvn evosuite:generate -Dcuts=artifact123.Calculator \
  -DextraArgs="-Dtarget_method_list=sum(II)I"
```
to generate test cases for method `append` you must run:
```
$ mvn evosuite:generate -Dcuts=artifact123.Calculator \
  -DextraArgs="-Dtarget_method_list=append(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
```

You can find more information about these descriptors (e.g., `Ljava/lang/String;`) in Sections 2.1.3 and 2.1.4 of the [ASM user guide](https://asm.ow2.io/asm4-guide.pdf).

---

I've just pushed a couple minor changes kinda related to this issue, so I would suggest you use the latest version of EvoSuite instead of version 1.0.6 (which is the latest stable version in the maven repository). To do so, you will have to clone EvoSuite repository, compile its source, and install it:
```
$ git clone https://github.com/EvoSuite/evosuite.git
$ cd evosuite
$ mvn clean install -DskipTests=true
```
Assuming everything goes well, you can then use version `1.0.7-SNAPSHOT` in your maven project.

--
Best,
Jose

**Comment by anandsubram** [comment]
Thank you.

Regarding the last comment "1.0.7-SNAPSHOT in your maven project." - Does it mean updating my pom.xml from "1.0.6" to "1.0.7-SNAPSHOT"? in both the below places? That didn't workout if that is the case. I got errors while performing Maven->Update Project in STS

 <dependency>
 <groupId>org.evosuite</groupId>
 <artifactId>evosuite-standalone-runtime</artifactId>
 <version>1.0.7-SNAPSHOT</version>
 <scope>test</scope>
</dependency>


<plugin>
        <groupId>org.evosuite.plugins</groupId>
        <artifactId>evosuite-maven-plugin</artifactId>
        <version>1.0.7-SNAPSHOT</version>
 </plugin>

**Comment by jose** [comment]
> Does it mean updating my pom.xml from "1.0.6" to "1.0.7-SNAPSHOT"?

Yes.

> in both the below places?

I don't know what you mean by _below places_. If you have followed the [EvoSuite Maven plugin tutorial](http://www.evosuite.org/documentation/maven-plugin/), you only need to specify _1.0.7-SNAPSHOT_ once.

> That didn't workout if that is the case. I got errors while performing Maven->Update Project in STS

Did you manage to compile and install EvoSuite from its source code?

**Comment by gofraser** [comment]
Since generating tests only for specific methods seems to be working I am closing this issue.
