### ISSUE TITLE
EvoSuite Maven plugin to generate test classes only for specific class, removes previously created test class

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#210]
Hi,

I created test class for individual classes using the below command. However I observe the following scenario
mvn evosuite:generate -Dcuts=org.foo.Bar

**Issue:-**
->Generate a test class for one class   - It generated both ESTest and Scaffolding classes
->Generate a new test class for another class - It generated both ESTest and Scaffolding classes for this. **However, it removes the ESTest class of previous class**

**Comment by jose** [comment]
Can you please provide more details? I'm not sure I'm understanding the issue you're reporting.

**Comment by anandsubram** [comment]
So I have 2 classes to generate the test class. I first ran the command mvn evosuite:generate -Dcuts=<Packagename.classname1> which generated the test class1(format classname_ESTest.java) and also the corresponding scaffolding.java class(which is needed for EvoSuite) for the first class. It generated in the path <Project Path>\.evosuite\best-tests\<package name> as expected. 

Then I ran the command mvn evosuite:generate -Dcuts=<Packagename.classname2> to generate the test class for the 2nd class. The test class and scaffolding class for the 2nd class was generated as expected. However it removed the test class of the 1st class from the path <Project Path>\.evosuite\best-tests\<package name>

**Comment by anandsubram** [comment]
Hi Jose,

So if I understand this is a bug you need to analyze further right? Can you provide any approx time lines for it if possible?

Regards
Anand

**Comment by jose** [comment]
After analysing the source code, IMO this is actually a feature and not a bug.

When you generate test cases for class `B` after generating tests for class `A`, EvoSuite assumes class `A` has been removed from the project and deletes all correspondent ESTest java files in the `.evosuite/best-tests` directory. (this mechanism is part of a more complex scenario than the one you're currently reporting)

So, I would suggest you use one of the following options to address this issue.

1. Specify all classes at the same time instead of just one, for example:
```
$ mvn evosuite:generate -Dcuts=org.foo.Bar,org.foo.Bar1,org.foo.Bar2,...
```

2. Generate test cases for one or more classes and copy all generated tests to a specific folder which by default points to where Maven searches for tests (i.e., `src/test/java`).
```
$ mvn evosuite:generate -Dcuts=org.foo.Bar,... evosuite:export
```
You can find more information about this `export` option in [here](http://www.evosuite.org/documentation/maven-plugin/) and [here](http://www.evosuite.org/documentation/tutorial-part-2/).

**Comment by anandsubram** [comment]
This really helps. Thanks a lot Jose!
