### ISSUE TITLE
setting separateClassLoader = false causes "no providers installed"

### ISSUE THREAD

**Issue by JimAthrs** [EvoSuite/evosuite#22]
Hello,
When we set the EvoRunnerParameters w/ the parameter separateClassLoader = false we get the attached exception during our unit test execution under maven.

OS: Win 7, Redhat
JDK: 1.8.0_51

Thanks,Jim

[estest_run_error.txt](https://github.com/EvoSuite/evosuite/files/223706/estest_run_error.txt)

**Comment by arcuri82** [comment]
Hi,
  I made an alpha release (still few things to fix and more testing before a proper / official release) where this issue should had been fixed. Version is 1.0.4-alpha1, on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cevosuite). If you use an executable jar instead of Maven, download the one from http://repo1.maven.org/maven2/org/evosuite/evosuite-master/1.0.4-alpha1/

can you confirm whether the issue you reported has been solved or not?  

cheers

Andrea

**Comment by JimAthrs** [comment]
Hello,

We’ve ran a test and looks to have worked. Thank you.


Thanks...Jim

Jim Snyder
