### ISSUE TITLE
How to generate failed test cases with EvoSuite？

### ISSUE THREAD

**Issue by KIKI57** [EvoSuite/evosuite#223]
### Context
Are all the test cases automatically generated by Evosuite will passed, whether the class being tested is reasonable or not？ When I was learning to use Evosuite, I wrote some wrong methods. Such as

### Steps to Reproduce 1
1. Class A
```
public class A {
	String test(B b) {
		return b.get(0);
	}
}
```
2.Interface B
```
public interface B {
	public abstract String get(int i) ;
}
```
### Current Result 1
 A_ESTest：
```
@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class A_ESTest extends A_ESTest_scaffolding {
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      A a0 = new A();
      B b0 = mock(B.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(b0).get(anyInt());
      String string0 = a0.test(b0);
      assertNull(string0);
  }
}
```
### Steps to Reproduce2
In a method where a divide by zero may occur, the generated test case even catch a exception to ensure that the test case passes.
### Current Result 2
```
@Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Case2 case2_0 = new Case2();
      // Undeclared exception!
      try { 
        case2_0.add(6, 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("test.Case2", e);
      }
  }

```
### EvoSuite Arguments
![EvoSuite Arguments](https://user-images.githubusercontent.com/38286577/44437287-105a0500-a5ec-11e8-9260-a1bab1547647.png)

### Expected result
Automatically generate test case that may fail and can be directly used by developers.

### Additional info
So is the automatically generated test case always passed, how to generate test cases by EvoSuite that may failed and can be directly used by developers?

**Comment by gofraser** [comment]
EvoSuite generates regression tests that will per definition pass on the version of the code they were generated on. This includes exceptions. If they fail, then it's because of flakiness, or bugs in EvoSuite.

There is an option `-Dcheck_contracts=true` in which case EvoSuite will do some basic checks and create failing tests for things like undeclared exceptions. The result will be a second test suite (`..._Failed_ESTest.java`). There may be some bugs with minimisation regarding these failing tests (the contract checking code hasn't been updated for a while), so please do create issues if you encounter specific bugs. In the Eclipse properties, this is the "Check generic object contracts" checkbox.
