### ISSUE TITLE
Low method coverage of public methods

### ISSUE THREAD

**Issue by Greg4cr** [EvoSuite/evosuite#29]
(Gordon and I have discussed this at SBST, posting here so there is an example)

On some classes, I am seeing low levels of method coverage of public methods, and am not sure the reason for it.

For example, see class https://github.com/mockito/mockito/blob/3eec7451d6c83c280743c39b39c77a179abb30f9/src/org/mockito/internal/invocation/InvocationMatcher.java

There is a fault that could be detected by covering method `public void captureArgumentsFrom(Invocation invocation)`
However, this method is not called by the generated EvoSuite tests. 

From EvoSuite output:
```
* Coverage analysis for criterion METHOD
* Coverage of criterion METHOD: 25%
* Total number of goals: 12
* Number of covered goals: 3
```

I know that method coverage uses a discrete fitness function (# covered methods), but I am curious why some methods would not be called.

**Comment by gofraser** [comment]
Just had a quick look, and it seems that EvoSuite is selecting the methods
alright, but almost all tests throw exceptions somewhere in the setup,
before the target methods can be invoked. To make it worse, Mockito seems
to use some plugin architecture that leads to classes being loaded during
test execution, and there are exceptions in the static constructors of some
of these classes. Once an exception has been thrown in a static
constructor, that class is unusable, and any further attempt to use it will
lead to a java.lang.NoClassDefFoundError on some essential classes such as
org.mockito.Answers (which is why we try to load all classes during
initialisation already). I don't know enough about Mockito to see if
there's a way around that...

Cheers,
Gordon

**Comment by Greg4cr** [comment]
Very interesting! Thank you for taking a closer look.

**Comment by gofraser** [comment]
Actually the exceptions in the static constructors were because I had
missed some dependencies on the classpath, sorry. But still the majority of
tests lead to exceptions, e.g. when trying to instantiate
a StubbedInvocationMatcher.
Gordon

**Comment by Greg4cr** [comment]
Going to close this issue as well. It is an interesting case where the class is difficult to test, but unlikely to be an actual fault in EvoSuite.
