### ISSUE TITLE
Error: Cannot consider [class] because it belongs to one of the packages Evosuite cannot currently handle

### ISSUE THREAD

**Issue by Akrabor** [EvoSuite/evosuite#3]
As said above, this error occurs while I try to generate test suites for different open source projects. One package in which it occurs is org.apache.log4j. Even the most simple class like 
    package org.apache.log4j;
    public class HelloWorld {
    }
does not "work".

However, this phenomenon occurs in every subpackage of org.apache.log4j, but classes located in org.apache or other subpackages of this are fine.

Do you know this problem, how it can be fixed or if there are other incompatible packages?

Concerning my setup:
java 1.8.0_45
ant 1.9.3
evosuite 1.0.1

**Comment by arcuri82** [comment]
Loggers are quite special. In theory, it could be possible to fix EvoSuite to be able to handle them. Unfortunately, it will likely be quite a bit of work to fix it. Considering that would affect only few packages, I doubt it will be done in any near future, unless this problem will affect more users that want to test loggers. In the particular case of org.apache.log4j, that is skipped because it is used internally by Ant. "Handling" that package would lead to problems when generated tests are run from Ant

**Comment by Akrabor** [comment]
Alright, thanks for the quick response.
Two questions result from your answer:

1) Is there a specific list of blocked packages? For me this sounds like there could be others that won`t work as well.

2) So, apparently the reason for the incompatibility is that evosuite does not want to instrument classes that are used to run tests. But could you not just use a different JVM / class loader if you would use fork=true?

**Comment by arcuri82** [comment]
1) They are defined in RuntimeInstrumentation#getPackagesShouldNotBeInstrumented() at:

https://github.com/EvoSuite/evosuite/blob/master/runtime/src/main/java/org/evosuite/runtime/instrumentation/RuntimeInstrumentation.java

2) I do not know the details (as I was not the one who added that package to the blacklist), but I remember it was not trivial
