### ISSUE TITLE
Generated test cases doesn't run with `mvn test` command

### ISSUE THREAD

**Issue by greenlaw110** [EvoSuite/evosuite#32]
I follow the evosuite [maven documentation](http://www.evosuite.org/documentation/maven-plugin/) to generate unit test cases for my project. Below is the command I've used:

``` bash
mvn -DmemoryInMB=2000 -Dcores=2 evosuite:generate evosuite:export  test
```

The tool takes around 1 hour to generate test cases for my project (with 9700 lines of Java code). However when it proceed to `mvn test` phase, all test cases failed with the same message:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in com.xxx.yyy.util.Messages_ESTest
com.xxx.yyy.util.Messages_ESTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalStateException: Trying to set up the sandbox while executing a test case
    at <evosuite>.<evosuite>(<evosuite>)
    at <evosuite>.<evosuite>(<evosuite>)
    at <evosuite>.<evosuite>(<evosuite>)
```

While running the generated test case in Intellij IDEA most of them can pass the test:

![img](http://i.stack.imgur.com/baSfM.png)

**Note** I am on the current `1.0.3` release.

Submit an issue report here as per the following answer to [this SO question](http://stackoverflow.com/questions/37536298/evosuite-failure-in-executing-test-cases/37552658):

![image](https://cloud.githubusercontent.com/assets/216930/15689347/eb0756cc-27c1-11e6-9cee-cdeb8bb238ee.png)

**Comment by arcuri82** [comment]
Hi,
  I made an alpha release (still few things to fix and more testing before a proper / official release) where this issue should had been fixed. Version is 1.0.4-alpha1, on Maven Central (http://search.maven.org/#search%7Cga%7C1%7Cevosuite). If you use an executable jar instead of Maven, download the one from http://repo1.maven.org/maven2/org/evosuite/evosuite-master/1.0.4-alpha1/

can you confirm whether the issue you reported has been solved or not?  

cheers

Andrea

**Comment by gofraser** [comment]
This seems to be fixed; I'll close this issue. If the problem re-appears, please re-open the issue.
