### ISSUE TITLE
EvoSuite Maven Repository seems to be down

### ISSUE THREAD

**Issue by rzo1** [EvoSuite/evosuite#43]
Hi,

is there the possibility to add the artifacts (older versions like 1.0.1 ; 1.0.2; 1.0.3) on Maven Central?
Old builds depend on it and if your repository is down, it will fail with an error.

Best,
rzo1

**Comment by arcuri82** [comment]
Hi,
  we are in the process of making a new release, which will include also having the jars on Maven Central. Current 1.0.4-alpha2 version is already on Central

http://search.maven.org/#search%7Cga%7C1%7Cevosuite

however, there is no plan to backward add also old, deprecated versions.

current repository fails due to hardware problems (I was told a disk failed), which is under investigation now. hopefully should be back online and running during the day

cheers

**Comment by rzo1** [comment]
Thanks for reporting so quickly :)

We just found 1.0.4-alpha2 on Maven Central and will use this.
